---
title: "Collaborative Etiquette"
author: "Rosemary Hartman"
date: "12/11/2019"
output: html_document
---

# Some basic ground rules

## Use issues to bring up things we need to work on

* __Don't be afraid!__ You don't need to submit code to contribute to the success of a project! Don't hold back on submitting issues, commenting on discussions and helping people out.

<br>


## For collaborators

* __Work in branches then send a PR any time you are working on files that aren't "yours".__ Just because you have full commit access doesn't mean you shouldn't use pull requests. PRs are a great way to solicit feedback from co-collaborators and to give them a nice overview of what's going on.

* __Review outstanding PRs.__ Feel free to merge any you see fit, and leave comments on anything that needs revisions. If you don't feel comfortable merging them, at least comment with a `:+1:` to signal your co-collaborators that it's passed your review.

* __Push directly for micro-fixes only.__ Only push to `master` for trivial updates that would be too noisy to notify your teammates of, such as typo fixes.

* __You can self-merge your PRs.__ Sometimes the rest of the team may be inactive, in which case, use your best judgement to self-merge PRs.

* __Keep history clean.__ No `--force` pushing on branches that aren't yours.

* __Communicate.__ You can use GitHub issues to communicate with your co-collaborators. Feel free to `@mention` them in issues.

* __Be nice.__ The collaborator team is nice, so we are all nice.

<br>


## Acknowledgements

> This is an extension to the [Open Open Source] manifesto.

[Open Open Source]: http://openopensource.org/

