---
title: "IEP Seasonal Monitoring Report Datasets"
author: "Rosemary Hartman"
date: "12/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## IEP Seasonal Monitoring Report: Datasets

### Dayflow: Net Delta Outflow index

Season: All

Study description: [DWR website](https://water.ca.gov/Programs/Environmental-Services/Compliance-Monitoring-And-Assessment/Dayflow-Data)

Data location: [CNRA portal](https://data.cnra.ca.gov/dataset/dayflow)

Data format: comma delimited files (.csv)

Range: 1929-present

Notes: For now, this is just a file generated by hand.


### Environmental Monitoring Program (DWR): Temperature, NO3-/NO2-/NH4+, Turbidity, Chlorophyll-a, Secchi Depth 

Season: All

Study description: [Bay-Delta Live](https://emp.baydeltalive.com/projects/11285)

Data location: [Bay-Delta Live](https://emp.baydeltalive.com/projects/11285) 

Data format: Microsoft Excel files (.xls)

Range: 1979-present

Notes: For now, these data have to be downloaded by hand.

### Zooplankton Survey (CDFW): Zooplankton

Season: All

Study description: [Bay Delta Live](https://emp.baydeltalive.com/projects/11281)

Data location: [CDFW FTP site](ftp://ftp.dfg.ca.gov/IEP_Zooplankton) OR [Bay-Delta Live](https://emp.baydeltalive.com/projects/11281)

Data format: Microsoft Excel files (.xlsx)

Range: 1979-present

Primary Data File(s): 

* 1972-2018CBMatrix.xlsx (tab = CB CPUE Matrix 1972-2018)
* 1972-2018PumpMatrix.xlsx (tab = Pump CPUE Matrix 1972-2018)
* 1972-2018MysidMatrix.xlsx (tab = Mysid CPUE Matrix 1972-2018)

Supporting Data File(s): 1972-2017MysidMatrix.xlsx (tab = StationLookup)

Notes: CPUE is available for all three sampling types (CB, Mysid, Pump) but not the BPUE or even the taxon-specific biomass estimates. I could ask April to add that info to the FTP site. In the meantime, I do have files for this. StationLookup is needed because the GPS coordinates for stations are needed to group stations into geographic regions. The StationLookup from the Mysid Net dataset works best because the StationLookup datasets for the other two surveys are just subsets of this one.


### Bay Study (CDFW): Longfin Smelt, Juvenile Sturgeon, Anchovy 

Season: Winter - Age 1+ longfin smelt, juvenile sturgeon. Summer - Anchovy

Study description: [CDFW Website](https://wildlife.ca.gov/Conservation/Delta/Bay-Study)

Data location: [CDFW FTP site](ftp://ftp.wildlife.ca.gov/BayStudy/CatchMatrices/)

Data format: Excel files (.xlsx)

Range: 1980-present

Primary Data File(s): 

* Bay Study_FishCatchMatrices_1980-2017.zip, which contains: 
* Bay Study_MWT_1980-2017_FishMarix.xlsx and 
* Bay Study_OT_1980-2017_FishMatrix.xlsx


### 20mm survey (CDFW): Delta Smelt Index

Season: Spring Report - recent trends

Study description: [CDFW Website](https://wildlife.ca.gov/Conservation/Delta/20mm-Survey)

Data location: [CDFW FTP site](ftp://ftp.dfg.ca.gov/Delta%20Smelt/)

Data format: Microsoft Access database (.accdb)

Range: 2004-present

Primary Data File(s): 20mm_New.accdb (probably should include all tables) 

Note: Queries for calculating CPUE and fish indecies are in [SQLQueries_20mm_New.accdb.pdf](data/SQLQueries_20mm_New.accdb.pdf) 

Primary Data File(s): 20mm_New.accdb (probably should include all tables) 


### Spring Kodiak Trawl (CDFW): Delta Smelt Index

Season: Winter Report - Recent trends

Study description: [CDFW Website](https://wildlife.ca.gov/Conservation/Delta/Spring-Kodiak-Trawl)

Data location: [CDFW FTP site](ftp://ftp.dfg.ca.gov/Delta%20Smelt/)

Data format: Microsoft Access database (.mdb)

Range: 2002-present

Primary Data File(s): SKT.mdb (probably should include all tables) 

Supporting Data File(s): NA


### Fall Midwater Trawl (CDFW): Age-0 Striped Bass, Delta Smelt, Longfin Smelt, American Shad

Season: Fall

Study description: [CDFW Website](https://wildlife.ca.gov/Conservation/Delta/Fall-Midwater-Trawl)

Data location: [CDFW website](http://www.dfg.ca.gov/delta/data/fmwt/indices.asp) OR
[CDFW FTP site](ftp://ftp.wildlife.ca.gov/TownetFallMidwaterTrawl/FMWT%20Data/)

Data format: Tables embedded in webpage, or calculated from excel (.xlsx) files

File: FMWT 1967-2018 Catch Matrix_updated.xlsx (zipped in FTP site)

Range: 1967-present


### Summer Townet (CDFW): Delta Smelt Index, Microcystis

Season: Summer

Study description: https://wildlife.ca.gov/Conservation/Delta/Townet-Survey

Data location: [FTP site](ftp://ftp.wildlife.ca.gov/TownetFallMidwaterTrawl/TNS%20MS%20Access%20Data/TNS%20data/) OR

[Website](http://www.dfg.ca.gov/delta/data/townet/indices.asp?species=3)

Data format: Tables embedded in web page (smelt indices), or calculate from Access database (Microcystis, or alternate route for smelt index)

Range: 1959-present

### Sturgeon Study Trammel Net Survey (CDFW): White Sturgeon

Season: Fall

Study description: [CDFW website](https://wildlife.ca.gov/Conservation/Delta/Sturgeon-Study)

Data location: [GitHub](https://github.com/jasondubois/SturgeonPopMetrics/blob/master/abundance/cpue_wst.csv)

Data format: csv

Range: 1967-present



### Grand Tab: Chinook Adult Population estimates

Season: Spring-Run for spring report, Fall-run for fall report

Study description: [CalFish](https://www.calfish.org/ProgramsData/Species/CDFWAnadromousResourceAssessment.aspx)

Data Location: [SacPas](http://www.cbr.washington.edu/sacramento/data/query_adult_grandtab.html)

Range: 1960-Present

Data format: queryable database. Imputs: “Download CSV only” Species: “Chinook, Spring”, Spawning type “In-River”. 

Direct-access link for [Spring-Run Chinook](http://www.cbr.washington.edu/sacramento/data/php/rpt/grandtab_graph.php?outputFormat=csv&species=Chinook%3ASpring&type=In-River&locType=location&location=Sacramento+and+San+Joaquin+River+Systems%3AAll%3AAll)

### Red Bluff Diversion Dam Rotary Screw Trap Monitoring (US FWS): Winter-run Chinook

Season: Winter

Study description: [FWS website](https://www.fws.gov/redbluff/rbdd_jsmp.html)

Final reports: [FWS website](https://www.fws.gov/redbluff/MSJM%20Reports/RST/rbdd_jsmp_annual.html)

Bi-weekly data: [SacPas](http://www.cbr.washington.edu/sacramento/data/query_redbluff_daily.html)

Data format: HTML/csv

For SacPAS [Red Bluff Juvenile Estimates Daily Table Query with Biweekly Totals](http://www.cbr.washington.edu/sacramento/data/query_redbluff_daily.html)

This is the call to generate the CSV file only of the calendar year based Red Bluff daily passage estimates. In this call, the biweekly estimates are turned off and water temperature unit is the default, Celsius. You would replace year value to query for different years. We have 2004 to present in the SacPAS database. 

Range: 2004-present

Format: query and .csv files


### Yolo Bypass Fish Monitoring Program (DWR): Splittail

Season: Spring

Study description: [EDI](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.233.1)

Data location: [EDI](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.233.1)

Data format: comma delimited files (.csv)

Range: 1998-present

Primary Data File(s): YBFMP_fish_and_water_quality_data_1998_2018.csv

Supporting Data File(s): 

* YBFMP_Fish_Taxonomy.csv
* YBFMP_Trap_Effort.csv
* YBFMP_Site_locations_latitude_and_longitude.csv


### Delta Juvenile Fish Monitoring Program (US Fish & Wildlife Service)

Season: Winter - Juvenile Chinook (Chipps), Spring - Juvenile Chinook, Summer - Native Cyprinids

Study description: [EDI](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.244.3)

Data location: [EDI](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.244.3)

Data format: comma delimited files (.csv)

Range: 1976-present

Primary Data File(s): DJFMP_fish_and_WQ.csv

Supporting Data File(s): DJFMP_Site_Locations.csv, DJFMP_Fish_Taxonomy.csv


