---
pagename: Metadata
---


# Metadata {#metadata}

### Interagency Ecological Program Seasonal Monitoring Report, Spring 2018 

* Version: 1.0
* Last Updated: 2020-03-09

Report developed by:

* Rosemary Hartman (California Department of Water Resources (CDWR, Rosemary.Hartman@water.ca.gov)
* Nicholas Rasmussen (CDWR)
* Lara Mitchell (US Fish and Wildlife Service)
* JohnFranco Saraceno (CDWR)
* David Bosworth (CDWR)
* Jason DuBois (California Department of Fish and Wildlife)
* Michael Koohafkan (CDWR)
* Louise Conrad (Delta Science Program)
* Sam Bashevkin (Delta Science Program)

## Overview
Long-term ecological surveys have been a core function of the Interagency Ecological Program (IEP) since the program’s inception in the 1970s. The IEP Seasonal Monitoring Report presents the full time series for selected water quality, plankton, and fisheries surveys conducted by IEP in a single graphical report. While the report is not a comprehensive view of all the data collected by IEP, it is intended to provide a general overview of the longevity and breadth of IEP survey work. A major goal of this report is to illustrate the scope of IEP surveys and emerging trends in the San Francisco Bay-Delta ecosystem to the public, potential science collaborators, and IEP and other resource agency managers and directors. The report is generated on a quarterly basis, with different set of ecosystem variables and surveys highlighted in each season. The report is developed by IEP scientists (including leads for monitoring surveys and the IEP Lead Scientist) and is reviewed by the IEP Science Management Team and Coordinators before online publication. 

## General Information

### Season Definitions
This report covers a suite of key IEP data sets relevant to the spring season, which we defined as the months of March, April, and May. For data sets collected throughout the year, such as water temperature, we only used data from this three-month period to generate graphs. For data sets that are season-specific, we include the entire sampling period, even if it does not overlap exactly with our season definition (for example, the 20mm Survey index includes data from March-July). Data from other times of year will be featured in the corresponding future seasonal reports (i.e., winter, summer, fall). The other seasons (for future reports) are defined as follows: Summer = June to August, Fall = September to November, and  Winter = December to February.

### Geographic Region Definitions
Many of the data sets in the report are represented by a panel of three plots, one for each of three geographic regions: San Pablo Bay, Suisun Bay, and the Sacramento-San Joaquin Delta. This subdivision of data sets is designed to facilitate comparison among major regions that differ in a variety of characteristics. San Pablo Bay includes data collected east of Point San Pablo and west of the Carquinez Straight. Suisun Bay includes data collected east of the Carquinez Straight and west of the town of Collinsville. The Delta includes data east of Collinsville. Data sets are represented as a single graph when the data are only collected within a single region (e.g., Net Delta Outflow) and for wide-ranging organisms that frequent multiple regions (e.g., Delta Smelt).

### Year Ranges
Most of the graphs in the report have an x-axis range from 1966 to 2018. This start year was selected because it is the year of initiation for the Fall Midwater Trawl survey, one of the longest-running surveys. Standardizing the year range on the x-axis facilitates visual comparison across data sets. The entire time series for nearly all data sets fits within this time range.  Data sets that started before 1966 were truncated in this report, for purposes of consistency within the report. The graphs in the Recent Trends section of the Spring report range from 2004 to 2018. 

### Calculations for Data Points
The points plotted on the graphs represent mean values. Means are generated by averaging data over the three months of the spring season for a given year (March-May) and across sites within a given region where relevant (e.g., water quality and plankton data sets). The dotted horizontal line indicates the average value over the entire period of record.

##Data Sets

### Flow
  + Data Source: Department of Water Resources, Environmental Planning and Information Branch
  + Metric Used: Net Delta Outflow Index, which is estimated using a summation of river inflows, precipitation, agricultural consumptive demand, and project exports. 
  + Year Range: 1966-2018. The entire data set includes 1929-2019 but was truncated to conform to the year range of the rest of the data sets in the report.
  + Additional Information:[https://www.water.ca.gov/Programs/Environmental-Services/Compliance-Monitoring-And-Assessment/Dayflow-Data](https://www.water.ca.gov/Programs/Environmental-Services/Compliance-Monitoring-And-Assessment/Dayflow-Data)

### Water Quality: Secchi depth, Temperature, Chlorophyll-a

  + Data Source: Department of Water Resources, Environmental Monitoring Program
  + Metric Used: Monthly discrete water quality data
  + Year Range: 1975 – 2018
  + Stations by Region
    * San Pablo: Stations = 4, years: 1975-2018
    * Suisun: Stations = 11, years: 1975-2017
    * Delta: Stations = 29, years: 1975-2017
  + Additional Information:[https://water.ca.gov/Programs/Environmental-Services/Water-Quality-Monitoring-And-Assessment](https://water.ca.gov/Programs/Environmental-Services/Water-Quality-Monitoring-And-Assessment)

### Zooplankton: Biomass of Calanoids, Cyclopoids, Cladocerans, and Mysids 

  + Data Source: California Department of Fish and Wildlife, Zooplankton Study
  + Metric Used: Biomass of zooplankton (milligrams of carbon per cubic meter) based on monthly surveys. 
  + Year Range: 1975 – 2018 
  + Stations by Region
    * San Pablo: Stations = 2, years: 1998-2018. Note: One station sampled consistently since 1998 and the other one since 2003.
    * Suisun: Stations = 6, years: 1975-2018
    * Delta: Stations = 8, years: 1975-2018
  + Additional Information:[https://www.wildlife.ca.gov/Conservation/Delta/Zooplankton-Study](https://www.wildlife.ca.gov/Conservation/Delta/Zooplankton-Study)

### Juvenile Winter-run Run Chinook: Chipps Island Trawl
  + Data Source: US Fish and Wildlife Service, Lodi Field Office, Delta Juvenile Fish Monitoring Program 
  + Metric Used: Mean catch per unit effort estimates for Winter-run Chinook. The calculation method is similar to that used by DJFMP staff for reporting.
  + Year Range:  1995-2017. 
      * Note: Although sampling at Chipps Island started in 1976, this year range was chosen for consistency with the range most recently reported on by DJFMP staff. 
  + Stations: 1
  + Additional Information:[https://www.fws.gov/lodi/juvenile_fish_monitoring_program/jfmp_index.htm](https://www.fws.gov/lodi/juvenile_fish_monitoring_program/jfmp_index.htm)


### Adult Spring-run Run Chinook: GrandTab

  + Data Source: CDFW’s Grand Tab database as queried from [SacPass](http://www.cbr.washington.edu/sacramento/data/query_adult_grandtab.html).
  + Metric Used: The CDFW Fisheries Branch Anadromous Resource Assessment Unit compiles annual population estimates of Chinook salmon, Oncorhynchus tshawytscha, in the Sacramento San Joaquin River system. The GrandTab report is a compilation of sources estimating the late-fall, winter, spring, and fall-run Chinook salmon total populations for streams surveyed. Estimates are based on counts of fish entering hatcheries and migrating past dams, carcass surveys, live fish counts, and ground and aerial redd counts. Estimates are provided by the California Department of Fish and Wildlife, the US Fish and Wildlife Service, the California Department of Water Resources, the East Bay Municipal Utilities District, the US Bureau of Reclamation, the Lower Yuba River Management Team, and the Fisheries Foundation of California.
  + Year Range: 1960-2018 
  + Additional Information:[https://wildlife.ca.gov/Conservation/Fishes/Chinook-Salmon/Anadromous-Assessment](https://wildlife.ca.gov/Conservation/Fishes/Chinook-Salmon/Anadromous-Assessment)

### Splittail: Yolo Bypass Screw Trap

  + Data Source: DWR’s Yolo Bypass Monitoring Study
  + Metric Used: Catch per unit effort (fish per hour), computed as the annual catch for the season divided by the rotary screw trap operational time.
  + Year Range: 1998 - 2018
  + Stations: 1
  + Additional Information: [https://portal.edirepository.org/nis/mapbrowse?packageid=edi.233.2](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.233.2)



